server:
  port: 8090
spring:
  rabbitmq:
    host: 192.168.199.128
    port: 5672
    virtual-host: /he
    username: he
    password: 123
    connection-timeout: 15000
    listener:
      simple:
        prefetch: 1       #此配置为work模式-公平分发的配置
    #    publisher-confirms: true         #生产者确认-旧版使用这个配置
    publisher-returns: true       #开启配置ReturnCallback才生效
    template:
      mandatory: true               #开启配置ReturnCallback才生效
    publisher-confirm-type: correlated      #生产者确认-新版使用这个配置，开启配置ConfirmCallback才生效

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rabbitmq-springboot?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    ###################DruidDataSource额外配置(在yml中)####################
    initialSize: 5
    minIdle: 10
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    ###################DruidDataSource额外配置(在properties中)####################
    ##下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    # druid.initialSize=5
    # druid.minIdle=10
    # druid.maxActive=300
    # #配置获取连接等待超时的时间
    # druid.maxWait=60000
    # #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    # druid.timeBetweenEvictionRunsMillis=60000
    # #配置一个连接在池中最小生存的时间，单位是毫秒
    # druid.minEvictableIdleTimeMillis=300000
    # druid.validationQuery=SELECT 1 FROM DUAL
    # druid.testWhileIdle=true
    # druid.testOnBorrow=false
    # druid.testOnReturn=false
    # #打开PSCache，并且指定每个连接上PSCache的大小
    # druid.poolPreparedStatements=true
    # druid.maxPoolPreparedStatementPerConnectionSize=20
    # #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # druid.filters=stat,wall,log4j
    # #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    # druid.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # #合并多个DruidDataSource的监控数据
    # druid.useGlobalDataSourceStat=true

#如果是使用druid数据源，此配置不会生效，详情看com.zhifei.reliabledelivery.config.DruidDataSourceConfig，同理，启动类上的@MapperScanner也是
#mybatis:
#  mapper-locations: mapper/*.xml
#  type-aliases-package: com.zhifei.reliabledelivery.entity